// <auto-generated />
using System;
using Enjaz.AI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enjaz.AI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiDbContext))]
    [Migration("20260704123005_InitialAi")]
    partial class InitialAi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enjaz.AI.Domain.AI.AiClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_request_id");

                    b.Property<int>("ComplexityId")
                        .HasColumnType("integer")
                        .HasColumnName("complexity_id");

                    b.Property<string>("ComplexityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("complexity_name");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_description");

                    b.Property<bool>("RequiresInspection")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_inspection");

                    b.Property<Guid>("ServiceCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_category_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("SuggestedAction")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("suggested_action");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ServiceCategoryId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ai_classifications", "ai");
                });

            modelBuilder.Entity("Enjaz.AI.Domain.AI.AiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_text");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response_json");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Feature");

                    b.ToTable("ai_requests", "ai");
                });
#pragma warning restore 612, 618
        }
    }
}
