// <auto-generated />
using System;
using Enjaz.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enjaz.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enjaz.Catalog.Domain.Catalog.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_en");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("services", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            NameAr = "إصلاح تسريب حنفية",
                            NameEn = "Faucet leak repair",
                            Slug = "faucet-leak-repair"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            NameAr = "كشف تسريب مياه",
                            NameEn = "Water leakage",
                            Slug = "water-leakage"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            NameAr = "إصلاح بريزة كهرباء",
                            NameEn = "Electrical outlet repair",
                            Slug = "electrical-outlet-repair"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            NameAr = "تركيب مفتاح كهرباء",
                            NameEn = "Switch installation",
                            Slug = "switch-installation"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            NameAr = "التكييف لا يبرد",
                            NameEn = "AC not cooling",
                            Slug = "ac-not-cooling"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            NameAr = "تنظيف وصيانة تكييف",
                            NameEn = "AC cleaning and maintenance",
                            Slug = "ac-cleaning-maintenance"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            NameAr = "إصلاح باب",
                            NameEn = "Door repair",
                            Slug = "door-repair"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            NameAr = "تركيب رفوف",
                            NameEn = "Shelf installation",
                            Slug = "shelf-installation"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            NameAr = "دهان غرفة",
                            NameEn = "Room painting",
                            Slug = "room-painting"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            NameAr = "معالجة رطوبة",
                            NameEn = "Moisture treatment",
                            Slug = "moisture-treatment"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            NameAr = "إصلاح غسالة",
                            NameEn = "Washing machine repair",
                            Slug = "washing-machine-repair"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            NameAr = "إصلاح ثلاجة",
                            NameEn = "Refrigerator repair",
                            Slug = "refrigerator-repair"
                        });
                });

            modelBuilder.Entity("Enjaz.Catalog.Domain.Catalog.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_en");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("service_categories", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            NameAr = "سباكة",
                            NameEn = "Plumbing",
                            Slug = "plumbing"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            NameAr = "كهرباء",
                            NameEn = "Electrical",
                            Slug = "electrical"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            NameAr = "تكييف",
                            NameEn = "AC",
                            Slug = "ac"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            NameAr = "نجارة",
                            NameEn = "Carpentry",
                            Slug = "carpentry"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            NameAr = "دهانات",
                            NameEn = "Painting",
                            Slug = "painting"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            NameAr = "أجهزة منزلية",
                            NameEn = "Appliances",
                            Slug = "appliances"
                        });
                });

            modelBuilder.Entity("Enjaz.Catalog.Domain.Catalog.ServiceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_en");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("service_tiers", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000011"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000011"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000011"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0001-0000-000000000012"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Simple",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0002-0000-000000000012"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Standard",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0003-0000-000000000012"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Complex",
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000012")
                        });
                });

            modelBuilder.Entity("Enjaz.Catalog.Domain.Catalog.Service", b =>
                {
                    b.HasOne("Enjaz.Catalog.Domain.Catalog.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Enjaz.Catalog.Domain.Catalog.ServiceTier", b =>
                {
                    b.HasOne("Enjaz.Catalog.Domain.Catalog.Service", "Service")
                        .WithMany("Tiers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Enjaz.Catalog.Domain.Catalog.Service", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Enjaz.Catalog.Domain.Catalog.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
