// <auto-generated />
using System;
using Enjaz.Pricing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enjaz.Pricing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260704123033_InitialPricing")]
    partial class InitialPricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enjaz.Pricing.Domain.Pricing.CommissionSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("is_default = TRUE AND is_active = TRUE");

                    b.ToTable("commission_settings", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CommissionRate = 0.15m,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            Name = "Default commission 15%"
                        });
                });

            modelBuilder.Entity("Enjaz.Pricing.Domain.Pricing.DepositRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DepositType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deposit_type");

                    b.Property<decimal>("DepositValue")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("deposit_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<decimal?>("MaximumDeposit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("maximum_deposit");

                    b.Property<decimal?>("MinimumDeposit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("minimum_deposit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("is_default = TRUE AND is_active = TRUE");

                    b.ToTable("deposit_rules", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepositType = "Percentage",
                            DepositValue = 0.20m,
                            IsActive = true,
                            IsDefault = true,
                            Name = "Default deposit 20%"
                        });
                });

            modelBuilder.Entity("Enjaz.Pricing.Domain.Pricing.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("BreakdownJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown_json");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("commission_amount");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("commission_rate");

                    b.Property<Guid?>("CommissionSettingId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_setting_id");

                    b.Property<int>("ComplexityId")
                        .HasColumnType("integer")
                        .HasColumnName("complexity_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EGP")
                        .HasColumnName("currency");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<Guid?>("DepositRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("deposit_rule_id");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("PricingRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_rule_id");

                    b.Property<bool>("RequiresInspection")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_inspection");

                    b.Property<Guid>("ServiceCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_category_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<decimal>("TechnicianPayoutAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("technician_payout_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("vat_amount");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("vat_rate");

                    b.Property<Guid?>("VatSettingId")
                        .HasColumnType("uuid")
                        .HasColumnName("vat_setting_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("price_snapshots", "pricing");
                });

            modelBuilder.Entity("Enjaz.Pricing.Domain.Pricing.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<int>("ComplexityId")
                        .HasColumnType("integer")
                        .HasColumnName("complexity_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EGP")
                        .HasColumnName("currency");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("RequiresInspection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_inspection");

                    b.Property<Guid>("ServiceCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_category_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFromUtc");

                    b.HasIndex("ServiceId", "ComplexityId")
                        .IsUnique()
                        .HasFilter("is_active = TRUE AND effective_to_utc IS NULL");

                    b.HasIndex("ServiceId", "ComplexityId", "IsActive");

                    b.ToTable("pricing_rules", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51000000-0000-0001-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0001-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0001-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0002-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0002-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0002-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0003-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0003-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0003-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0004-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0004-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0004-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0005-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0005-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0005-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0006-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0006-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0006-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0007-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0007-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0007-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0008-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0008-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0008-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0009-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0009-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0009-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0010-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0010-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0010-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0011-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0011-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0011-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0012-0001-000000000001"),
                            BasePrice = 150m,
                            ComplexityId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0012-0002-000000000001"),
                            BasePrice = 250m,
                            ComplexityId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = false,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0012-0003-000000000001"),
                            BasePrice = 0m,
                            ComplexityId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EGP",
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresInspection = true,
                            ServiceCategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000012")
                        });
                });

            modelBuilder.Entity("Enjaz.Pricing.Domain.Pricing.VatSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppliesOn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("applies_on");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("is_default = TRUE AND is_active = TRUE");

                    b.ToTable("vat_settings", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            AppliesOn = "Commission",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFromUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            Name = "Default VAT 14%",
                            VatRate = 0.14m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
