// <auto-generated />
using System;
using Enjaz.Notifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enjaz.Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260704183403_InitialNotifications")]
    partial class InitialNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enjaz.Notifications.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsRead");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", "notifications");
                });

            modelBuilder.Entity("Enjaz.Notifications.Domain.Notifications.NotificationDeliveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("Recipient")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recipient");

                    b.Property<string>("RequestJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_json");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("notification_delivery_logs", "notifications");
                });

            modelBuilder.Entity("Enjaz.Notifications.Domain.Notifications.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body_template");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("ar")
                        .HasColumnName("language");

                    b.Property<string>("TitleTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_template");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Channel", "Language")
                        .IsUnique()
                        .HasFilter("is_active = true");

                    b.ToTable("notification_templates", "notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000801"),
                            BodyTemplate = "تم إنشاء طلبك رقم {{jobNumber}} بنجاح.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تم إنشاء الطلب",
                            Type = "JobCreated"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000802"),
                            BodyTemplate = "تم تحديث حالة طلبك رقم {{jobNumber}} إلى {{status}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تحديث حالة الطلب",
                            Type = "JobStatusChanged"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000803"),
                            BodyTemplate = "تم تعيين فني لطلبك رقم {{jobNumber}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تم تعيين فني",
                            Type = "TechnicianAssigned"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000804"),
                            BodyTemplate = "تم قبول المهمة رقم {{jobNumber}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تم قبول المهمة",
                            Type = "AssignmentAccepted"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000805"),
                            BodyTemplate = "تم رفض المهمة رقم {{jobNumber}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تم رفض المهمة",
                            Type = "AssignmentRejected"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000806"),
                            BodyTemplate = "تم إلغاء طلبك رقم {{jobNumber}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تم إلغاء الطلب",
                            Type = "JobCancelled"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000807"),
                            BodyTemplate = "تم إنشاء رابط الدفع لطلبك رقم {{jobNumber}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تم إنشاء رابط الدفع",
                            Type = "PaymentCheckoutCreated"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000808"),
                            BodyTemplate = "تم استلام دفعتك لطلب رقم {{jobNumber}} بمبلغ {{amount}} {{currency}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تم الدفع بنجاح",
                            Type = "PaymentSucceeded"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000809"),
                            BodyTemplate = "تعذر إتمام الدفع لطلب رقم {{jobNumber}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "فشل الدفع",
                            Type = "PaymentFailed"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000810"),
                            BodyTemplate = "تم تحديث محفظتك بمبلغ {{amount}} {{currency}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "تم تحديث المحفظة",
                            Type = "WalletUpdated"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000811"),
                            BodyTemplate = "لديك ربح قيد الانتظار بمبلغ {{amount}} {{currency}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "ربح قيد الانتظار",
                            Type = "TechnicianEarningPending"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000812"),
                            BodyTemplate = "أصبح ربحك متاحا بمبلغ {{amount}} {{currency}}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Language = "ar",
                            TitleTemplate = "ربح متاح",
                            Type = "TechnicianEarningAvailable"
                        });
                });

            modelBuilder.Entity("Enjaz.Notifications.Domain.Notifications.PushDeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("push_device_tokens", "notifications");
                });

            modelBuilder.Entity("Enjaz.Notifications.Domain.Notifications.UserNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Channel")
                        .IsUnique();

                    b.ToTable("user_notification_preferences", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
